"""empty message

Revision ID: 44c5c35e3850
Revises: 
Create Date: 2020-04-04 22:01:53.392845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44c5c35e3850'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompts')
    op.drop_table('admin')
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tag_text', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('tag_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('admin',
    sa.Column('admin_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=56), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=56), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('prompts',
    sa.Column('prompt_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('prompt_text', mysql.VARCHAR(length=2500), nullable=False),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('prompt_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
